# Site settings

#google_analytics: UA-NNNNNNNN-N

title: "gloof's hideout"

header_pages:
  - index.md
  - writeups.md
  - projects.md

footer: 'follow me on <a href="https://twitter.com/gloof11">twitter</a>'

style: dark
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
