# Site settings

title: "gloof's hideout"

header_pages:
  - index.md
  - blog.md
  - projects.md
  - writeups.md
  - music.md

style: dark
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
